// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBANaJd2f464biMqZ-YeaIYZF85a4WNI4k',
    appId: '1:881565800464:web:481410e599989af8d3d295',
    messagingSenderId: '881565800464',
    projectId: 'imgpicker-788dd',
    authDomain: 'imgpicker-788dd.firebaseapp.com',
    storageBucket: 'imgpicker-788dd.appspot.com',
    measurementId: 'G-C2JYJD00FN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqISx9Wy4Ccz88GGgp8P_BGpMYm9Gq8RA',
    appId: '1:881565800464:android:1e1597e8cd5e86e4d3d295',
    messagingSenderId: '881565800464',
    projectId: 'imgpicker-788dd',
    storageBucket: 'imgpicker-788dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2SqoMYkiQdatY6HaFw-X76uWMzsGNmSg',
    appId: '1:881565800464:ios:c5724e4f1c571baad3d295',
    messagingSenderId: '881565800464',
    projectId: 'imgpicker-788dd',
    storageBucket: 'imgpicker-788dd.appspot.com',
    iosBundleId: 'com.example.serviceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2SqoMYkiQdatY6HaFw-X76uWMzsGNmSg',
    appId: '1:881565800464:ios:c5724e4f1c571baad3d295',
    messagingSenderId: '881565800464',
    projectId: 'imgpicker-788dd',
    storageBucket: 'imgpicker-788dd.appspot.com',
    iosBundleId: 'com.example.serviceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBANaJd2f464biMqZ-YeaIYZF85a4WNI4k',
    appId: '1:881565800464:web:731a61a25ab89731d3d295',
    messagingSenderId: '881565800464',
    projectId: 'imgpicker-788dd',
    authDomain: 'imgpicker-788dd.firebaseapp.com',
    storageBucket: 'imgpicker-788dd.appspot.com',
    measurementId: 'G-95HT5K4SBF',
  );
}
